### ISSUE TITLE
Remove use of HTTParty

### ISSUE THREAD

**Issue by hawkins** [hawkins/lard#4]
Honestly, this lib has been something of a headache with its less-than-stellar docs and presumptuous api to say the least, so I've boiled the HTTP calls down to something pretty simple such that we can hopefully remove httparty pretty easily.

On top of all that, I'd like to get back support for ruby < 2, I think I can justify replacing `httparty` with `net/http` or another lib that's a bit lower level and with lower dependencies.

### Concerns:

- 3xx codes
  - If I remember right, `POST https://larder.io/api/1/@me/*` hit 301's to somewhere, so I need whatever interface I scrap together to follow redirects and maintain HTTP verbs throughout redirections.
- Easily infer errors
  - `res[:error]` is nice - I don't want to lose that semantic response if possible

**Comment by hawkins** [comment]
That might be it! I didn't look very closely at the redirection even when I noticed it, but I know I have not been using trailing slashes, so I'm hopeful. I'll give it a go with them and see what happens 😄 👍

**Comment by joshsharp** [comment]
Okay cool. If you're not sure, check the URL in the docs — they should always be specified there, so if there are any missing, that's on me.
